### ISSUE TITLE
Issue 1.2: Sign in Page

### ISSUE THREAD

**Issue by khangvchung** [ucsb-cs184-f24/team03-roomi#12]
Sign In Page
- [x] Input for email
- [x] Input for secure password
- [x] Sign In button
- [x] Button to sign up

**Comment by Bennyyyyy** [comment]
Sign In Page
- [ ] Input for email
- [ ] Input for secure password
- [ ] Sign In button

Sign Up Page
- [ ] Input for email
- [ ] Input for secure password
- [ ] Input for confirm password with check
- [ ] Sign Up button
